import React from 'react'

function About() {
  return (
    <div>

      <h1 className='pt-16 text-center text-teal-950 text-4xl'>Welcome to DevDiaries</h1>

      <p className='pt-20 pr-32 pl-32 pb-20 text-center'>Lorem ipsum dolor sit amet consectetur adipisicing elit. Iste ab, enim nisi totam reprehenderit cumque mollitia obcaecati consequatur animi temporibus eius rem nemo, quidem architecto unde in voluptates veniam iure? In quisquam inventore corrupti dignissimos, mollitia modi, ipsam sunt quos voluptates vero vel quod quasi accusamus aperiam quia! Accusamus nobis porro consequatur ipsa quas molestias officiis doloribus quibusdam reprehenderit quae inventore, vero tenetur quo repellendus dolorum asperiores? Laudantium, ab odio ratione rem beatae nisi possimus nulla numquam doloremque accusamus facere aperiam dolores nostrum, dignissimos nam, assumenda suscipit. Blanditiis harum officia ullam consectetur nemo mollitia sed repellat voluptate quidem nam impedit, quaerat excepturi autem deleniti eveniet? Sunt cupiditate veritatis illo error excepturi nobis numquam doloremque cumque atque. Nobis natus corporis, quia tempore, recusandae quidem officia fuga, doloremque repellendus error veniam! Vero reprehenderit veniam quasi voluptas aliquam nam beatae aut, repudiandae eum amet? 
        <p> Dolorem eaque illo tempore incidunt dicta ullam itaque numquam ratione magnam est, ipsam laudantium sed? Quibusdam temporibus aspernatur ullam quo, rerum atque ea doloremque quia a quisquam dolor odio vel ut magnam reiciendis voluptates voluptatem tempora rem repellat ipsam! Explicabo eligendi possimus deleniti rerum sunt atque nostrum praesentium dolorum, sit delectus dolore quis cupiditate fugit, laudantium, corrupti illum veritatis non. Minima, animi! Quos optio reiciendis temporibus aspernatur, quisquam unde quaerat ipsam laborum quam, libero aliquam. Atque, reiciendis molestiae vel, ut tenetur veniam, expedita rem neque vero minima minus sed adipisci voluptate eum delectus. Rerum dicta ut ex totam neque, </p>fuga unde ratione veritatis cum optio quas deserunt. Suscipit rem quod cupiditate voluptates. Ratione harum porro a nemo eveniet esse praesentium, blanditiis expedita ex cupiditate delectus excepturi tenetur iure voluptates rem, ducimus modi fugiat beatae. Vero architecto non iusto! Assumenda, at? Doloremque perspiciatis earum culpa odit pariatur itaque iste enim aut quisquam iure accusantium, tempore minima tenetur mollitia accusamus quasi architecto veritatis. Aut, ab nemo numquam perferendis possimus corrupti vitae soluta facere eum architecto ipsam nulla repellendus. Vel quia velit repellat debitis, facere corporis, consectetur inventore vero possimus ex consequuntur nihil molestiae ipsam provident minima laudantium ab labore architecto id fuga laborum quaerat exercitationem doloremque dolorem? Molestias voluptates sit sapiente nihil, corporis <p> doloribus laborum ullam facere quia quae quis ut officia animi voluptatem eligendi porro nemo ipsum. Ipsa quibusdam rerum cumque fuga, similique quae distinctio atque iusto quisquam incidunt dolorum obcaecati sunt quod earum, esse est corrupti aperiam non explicabo culpa facere, quo minus autem quos? Maiores ducimus voluptatem reiciendis rem harum voluptatibus velit veritatis temporibus libero odio! Eligendi quisquam temporibus aliquam quibusdam, optio necessitatibus commodi et adipisci neque aspernatur deserunt. Rerum nesciunt sapiente maxime deleniti ex illo? Ab temporibus quo quasi architecto nobis laboriosam numquam at! Expedita odio laudantium molestias aspernatur </p> totam eveniet eos, officia consectetur ex, dicta maxime iste rerum error nobis, vitae autem sit omnis voluptatibus dolor rem velit deserunt dignissimos pariatur minima. Dolorem, facilis libero ut illum atque dolore, dolores magnam commodi, voluptates at hic possimus inventore omnis provident in voluptatibus nihil nemo ab maxime quis odio quae quos quidem! Doloremque consequuntur dolores ipsum aperiam ducimus.</p>
    </div>
  )
}

export default About